{"name": "test_sub_003", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_1st_file.Test_my001 object at 0x0000019D9E549550>\n\n    def test_sub_003(self):\n        a= 10\n        b= 5\n        sub= a-b\n        print(\"Sub of a and b :\", sub)\n        if sub == 6:\n            assert True\n        else:\n>           assert False\nE           assert False\n\nPytest_my\\test_1st_file.py:38: AssertionError"}, "start": 1690611095661, "stop": 1690611095661, "uuid": "0b5fe5e5-9099-402d-866a-e22323f24b77", "historyId": "b4a16c17f935adfff31f2aaa4a88f0b1", "testCaseId": "b4a16c17f935adfff31f2aaa4a88f0b1", "fullName": "Pytest_my.test_1st_file.Test_my001#test_sub_003", "labels": [{"name": "parentSuite", "value": "Pytest_my"}, {"name": "suite", "value": "test_1st_file"}, {"name": "subSuite", "value": "Test_my001"}, {"name": "host", "value": "DESKTOP-QRGRBTF"}, {"name": "thread", "value": "9828-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Pytest_my.test_1st_file"}]}